name: cmake-for-macos

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  Qt5_DIR: /opt/homebrew/opt/qt@5

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Install Deps
      run: brew install qt@5

    - name: Configure CMake
      run: cmake ${{github.workspace}}/src -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}}
    
    - name: Compress
      run: zip -r9 ${{github.workspace}}/candle.zip ${{github.workspace}}/Candle.app/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: candle.arm64.zip
        path: candle.zip
    
    - name: Create Release
      run: gh release create './candle.zip#MacOS15-arm64'
